CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`businessType` varchar(64),
	`businessNumber` varchar(32),
	`corporateNumber` varchar(32),
	`establishedDate` varchar(32),
	`businessPhone` varchar(32),
	`employeeCount` varchar(32),
	`industry` varchar(128),
	`officeOwnership` varchar(16),
	`businessAddress` text,
	`deposit` varchar(32),
	`monthlyRent` varchar(32),
	`hasAdditionalBranch` varchar(8),
	`additionalBranchNumber` varchar(64),
	`representativeName` varchar(128),
	`birthDate` varchar(32),
	`contactNumber` varchar(32),
	`telecom` varchar(32),
	`homeAddress` text,
	`homeOwnership` varchar(16),
	`education` varchar(64),
	`major` varchar(128),
	`career1` text,
	`career2` text,
	`hasFinancialDelinquency` varchar(8),
	`hasTaxDelinquency` varchar(8),
	`kcbScore` varchar(16),
	`niceScore` varchar(16),
	`hasExportSales` varchar(8),
	`hasPlannedExport` varchar(8),
	`currentYearSales` varchar(32),
	`year25Sales` varchar(32),
	`year24Sales` varchar(32),
	`year23Sales` varchar(32),
	`currentYearExport` varchar(32),
	`year25Export` varchar(32),
	`year24Export` varchar(32),
	`year23Export` varchar(32),
	`jungJinGong` varchar(32),
	`soJinGong` varchar(32),
	`sinbo` varchar(32),
	`gibo` varchar(32),
	`jaedan` varchar(32),
	`companyCollateral` varchar(32),
	`ceoCredit` varchar(32),
	`ceoCollateral` varchar(32),
	`certifications` text,
	`hasPatent` varchar(8),
	`patentCount` varchar(16),
	`patentDetails` text,
	`hasGovSupport` varchar(8),
	`govSupportCount` varchar(16),
	`govSupportDetails` text,
	`coreItem` text,
	`salesRoute` text,
	`competitiveness` text,
	`marketStatus` text,
	`processDetail` text,
	`targetCustomer` text,
	`revenueModel` text,
	`futurePlan` text,
	`requiredFunding` varchar(32),
	`fundingPlanDetail` text,
	`memo` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyId` int NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`type` varchar(32) NOT NULL,
	`title` varchar(512) NOT NULL,
	`sectionsJson` text NOT NULL,
	`matchingSummaryJson` text,
	`companySummaryJson` text,
	`status` varchar(16) NOT NULL DEFAULT 'completed',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reports_id` PRIMARY KEY(`id`)
);
